# Generated by Django 5.0.6 on 2024-07-08 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvr', '0002_alter_customuser_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wastepaper_count', models.IntegerField(default=0, verbose_name='Макулатура (количество)')),
                ('wastepaper_needs_exportation', models.BooleanField(default=False, verbose_name='Макулатура (нужен вывоз)')),
                ('cullet_count', models.IntegerField(default=0, verbose_name='Стеклобой (количество)')),
                ('cullet_needs_exportation', models.BooleanField(default=False, verbose_name='Стеклобой (нужен вывоз)')),
                ('polyethylene_count', models.IntegerField(default=0, verbose_name='Полиэтилен (количество)')),
                ('polyethylene_needs_exportation', models.BooleanField(default=False, verbose_name='Полиэтилен (нужен вывоз)')),
                ('scrap_metal_count', models.IntegerField(default=0, verbose_name='Металлолом (количество)')),
                ('scrap_metal_needs_exportation', models.BooleanField(default=False, verbose_name='Металлолом (нужен вывоз)')),
                ('date_time_updated', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего редактирования')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bvr.procurementsector', verbose_name='Sector')),
            ],
            options={
                'verbose_name': 'Остаток материальных ресурсов',
                'verbose_name_plural': 'Остатки материальных ресурсов',
                'ordering': ('sector',),
            },
        ),
    ]
