# Generated by Django 5.0.6 on 2024-07-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvr', '0002_alter_customuser_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remains',
            options={'ordering': ('-wastepaper_needs_exportation', '-cullet_needs_exportation', '-polyethylene_needs_exportation', '-scrap_metal_needs_exportation'), 'verbose_name': 'Остаток материальных ресурсов', 'verbose_name_plural': 'Остатки материальных ресурсов'},
        ),
        migrations.AlterField(
            model_name='procurementsector',
            name='sector_address',
            field=models.TextField(verbose_name='Sector address'),
        ),
    ]
