# Generated by Django 5.0.6 on 2024-07-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bvr", "0003_alter_remains_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procurementsector",
            name="sector_number",
            field=models.IntegerField(verbose_name="Sector Number"),
        ),
    ]
