# Generated by Django 5.0.6 on 2024-07-08 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvr', '0003_remains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remains',
            name='sector',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bvr.procurementsector', verbose_name='Sector'),
        ),
    ]
