# Generated by Django 5.0.6 on 2024-07-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvr', '0004_alter_remains_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementsector',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
    ]
