# Generated by Django 5.0.6 on 2024-07-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bvr", "0004_alter_procurementsector_sector_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remains",
            name="cullet_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Стеклобой (количество)"
            ),
        ),
        migrations.AlterField(
            model_name="remains",
            name="polyethylene_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Полиэтилен (количество)"
            ),
        ),
        migrations.AlterField(
            model_name="remains",
            name="scrap_metal_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Металлолом (количество)"
            ),
        ),
        migrations.AlterField(
            model_name="remains",
            name="wastepaper_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Макулатура (количество)"
            ),
        ),
    ]
